### ISSUE TITLE
FR: Gas gebruik berekend  op API

### ISSUE THREAD

**Issue by SamJongenelen** [mrWheel/DSMRloggerAPI#22]
Zou het mogelijk zijn om het gas gebruik berekend op de api te krijgen? Mijn doel is om het gas gebruik op een _24u chart_ te laten zien, telijk met energie gebruik en levering (home assistant).

Ik gebruik MQTT om te publishen vanaf de logger. Daar wordt wel ` Gas_delivered`  gepost, maar dat is de som van het gebruik. Ik zag dat het in de UI al ergens berekend getoond wordt:
![image](https://user-images.githubusercontent.com/3382443/79213921-4c3d8000-7e4a-11ea-9086-97a674f1c1d9.png)

Maar ik zie deze waarden niet op de rest API: http://dsmr-api.local/api/v1/sm/fields (en ook niet op mqtt).

Is het mogelijk om het (berekend, iets als _gas_used_today_ ) gas gebruik (bijv. in Home Assistant te krijgen, door de DSMRLoggerAPI te gebruiken?

Overigens, bedankt voor de DSMR-logger. Werkt perfect!

DSMR4, DSMR logger v4.5 met DSMRLoggerAPI (huidige laatste versie)

**Comment by vnijhuis** [comment]
Hallo,

Op de documentatie pagina van de API software staat een beknopte versie van hoe data in Home Assistent te krijgen. 

Ik heb ook beloofd aan Willem om te helpen aan wat duidelijke documentatie om het geheel met mooie dashboards in elkaar te zetten. Helaas door wat leek een griepje, bleek toch erger, is dat nog niet gelukt. 

Houdt ook zijn documentatie in de gaten ik merkte al dat deze goed ik to date word gehouden als er nieuwe functionaliteit bij komt oid.

**Comment by SamJongenelen** [comment]
Hoi, die heb ik gebruik voor stroom gebruik en levering inderdaad. Deze data (bijv dus gas_delivered_today) zit niet in mqtt data

**Comment by SamJongenelen** [comment]
https://github.com/mrWheel/DSMRloggerAPI-DOCS/pull/2

**Comment by vnijhuis** [comment]
Dit wordt inderdaad momenteel niet meegegeven in de mqtt. Je kan dit eenvoudig zelf uitrekenen. Ik haal de settings met een rest call uit de logger ieder uur. en gebruik die waardes om een som te maken met de totale kosten:

```
configuration.yaml - 
utility_meter:
  gas_delivered_hourly_in_m3:
    source: sensor.gas_delivered
    cycle: hourly
  gas_delivered_daily_in_m3:
    source: sensor.gas_delivered
    cycle: daily
  gas_delivered_weekly_in_m3:
    source: sensor.gas_delivered
    cycle: weekly  
  gas_delivered_monthly_in_m3:
    source: sensor.gas_delivered
    cycle: monthly
  gas_delivered_quarterly_in_m3:
    source: sensor.gas_delivered
    cycle: quarterly
  gas_delivered_yearly_in_m3:
    source: sensor.gas_delivered
    cycle: yearly

Aparte sensors.yaml
- platform: rest
  name: "DSMR settings"
  resource: http://dsmr-api.local/api/v1/dev/settings
  method: GET
  json_attributes:
    - settings
  value_template: '{{ value_json.settings[0].value }}'
  scan_interval: 3600

- platform: template
  sensors:
    delivered_daily_gas_cost:
      friendly_name: Gas kosten per dag
      value_template: '{{ states.sensor.dsmr_settings.attributes["settings"][5].value * states("sensor.gas_delivered_daily_in_m3")|float }}'
```

Dit geeft voor mij een dagelijkse kosten berekening. 
Maar je kan dus ook verder gaan met de berekingen uiteraard.
